/*
**
** The C code is generated by ATS/Postiats
** The starting compilation time is: 2015-5-15: 14h:22m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_HEADER_NONE */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER
//
#include _ATS_CCOMP_PRELUDE_USER
//
#endif /* _ATS_CCOMP_PRELUDE_USER */

/*
staload-prologues(beg)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/pointer.dats: 1533(line=44, offs=1) -- 1572(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer_fixed.dats: 1641(line=51, offs=1) -- 1680(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/memory.dats: 1410(line=38, offs=1) -- 1449(line=39, offs=32)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/string.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/strptr.dats: 1609(line=48, offs=1) -- 1648(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/strptr.dats: 1671(line=52, offs=1) -- 1718(line=52, offs=48)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1613(line=48, offs=1) -- 1652(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1675(line=52, offs=1) -- 1722(line=52, offs=48)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 1636(line=51, offs=1) -- 1675(line=51, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1745(line=56, offs=1) -- 1783(line=56, offs=39)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 1861(line=61, offs=1) -- 1901(line=61, offs=41)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/stat.sats: 1390(line=36, offs=1) -- 1431(line=38, offs=3)
*/

#include "libc/sys/CATS/stat.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/stat.sats: 1776(line=53, offs=1) -- 1818(line=54, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/filebas.dats: 15159(line=816, offs=1) -- 15189(line=816, offs=31)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1380(line=35, offs=1) -- 1418(line=37, offs=3)
*/

#include "libc/CATS/stdio.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/SATS/stdio.sats: 1791(line=56, offs=1) -- 1833(line=58, offs=27)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/libc/sys/SATS/types.sats: 1390(line=36, offs=1) -- 1432(line=38, offs=3)
*/

#include "libc/sys/CATS/types.cats"
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list.dats: 1527(line=44, offs=1) -- 1566(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list.dats: 1567(line=45, offs=1) -- 1613(line=45, offs=47)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt.dats: 1536(line=44, offs=1) -- 1575(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt_mergesort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/list_vt_quicksort.dats: 1546(line=44, offs=1) -- 1585(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array.dats: 1534(line=44, offs=1) -- 1573(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array.dats: 1574(line=45, offs=1) -- 1616(line=45, offs=43)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array_bsearch.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/array_quicksort.dats: 1531(line=44, offs=1) -- 1570(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/arrayptr.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/arrayref.dats: 1532(line=44, offs=1) -- 1571(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrix.dats: 1535(line=44, offs=1) -- 1574(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrixptr.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/matrixref.dats: 1538(line=44, offs=1) -- 1577(line=44, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/stream.dats: 1570(line=48, offs=1) -- 1609(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/stream_vt.dats: 1573(line=48, offs=1) -- 1612(line=48, offs=40)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/unsafe.dats: 1532(line=44, offs=1) -- 1566(line=44, offs=35)
*/
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/checkast.dats: 1531(line=44, offs=1) -- 1570(line=45, offs=32)
*/
/*
/home/hwwu/GitHub/msgpack-ats/pack.sats: 1(line=1, offs=1) -- 89(line=6, offs=3)
*/

#ifndef __MSGPACK
#define __MSGPACK
#include "msgpack-c/include/msgpack.h"
#endif
/*
/home/hwwu/GitHub/msgpack-ats/pack.sats: 92(line=9, offs=1) -- 113(line=9, offs=22)
*/
/*
/home/hwwu/GitHub/msgpack-ats/object.sats: 1(line=1, offs=1) -- 89(line=6, offs=3)
*/

#ifndef __MSGPACK
#define __MSGPACK
#include "msgpack-c/include/msgpack.h"
#endif
/*
/home/hwwu/GitHub/msgpack-ats/unpack.sats: 1(line=1, offs=1) -- 89(line=6, offs=3)
*/

#ifndef __MSGPACK
#define __MSGPACK
#include "msgpack-c/include/msgpack.h"
#endif
/*
/home/hwwu/GitHub/msgpack-ats/unpack.sats: 92(line=9, offs=1) -- 113(line=9, offs=22)
*/
/*
/home/hwwu/GitHub/msgpack-ats/object.sats: 1(line=1, offs=1) -- 89(line=6, offs=3)
*/

#ifndef __MSGPACK
#define __MSGPACK
#include "msgpack-c/include/msgpack.h"
#endif
/*
/home/hwwu/GitHub/msgpack-ats/unpack.sats: 365(line=20, offs=1) -- 480(line=27, offs=3)
*/


static inline msgpack_object msgpack_unpacked_data (msgpack_unpacked* result)
{
    return result->data;
}

/*
/home/hwwu/GitHub/msgpack-ats/sbuffer.sats: 1(line=1, offs=1) -- 89(line=6, offs=3)
*/

#ifndef __MSGPACK
#define __MSGPACK
#include "msgpack-c/include/msgpack.h"
#endif
/*
/home/hwwu/GitHub/msgpack-ats/sbuffer.sats: 205(line=14, offs=1) -- 224(line=14, offs=20)
*/
/*
/home/hwwu/GitHub/msgpack-ats/pack.sats: 1(line=1, offs=1) -- 89(line=6, offs=3)
*/

#ifndef __MSGPACK
#define __MSGPACK
#include "msgpack-c/include/msgpack.h"
#endif
/*
/home/hwwu/GitHub/msgpack-ats/pack.sats: 92(line=9, offs=1) -- 113(line=9, offs=22)
*/
/*
/home/hwwu/GitHub/msgpack-ats/object.sats: 1(line=1, offs=1) -- 89(line=6, offs=3)
*/

#ifndef __MSGPACK
#define __MSGPACK
#include "msgpack-c/include/msgpack.h"
#endif
/*
/home/hwwu/GitHub/msgpack-ats/sbuffer.sats: 2583(line=100, offs=1) -- 2772(line=112, offs=3)
*/


static inline size_t msgpack_sbuffer_size(msgpack_sbuffer* sbuf)
{
	return sbuf->size;
}

static inline char* msgpack_sbuffer_buffer(msgpack_sbuffer* sbuf) 
{
	return sbuf->data;
}

/*
/home/hwwu/GitHub/msgpack-ats/object.sats: 1(line=1, offs=1) -- 89(line=6, offs=3)
*/

#ifndef __MSGPACK
#define __MSGPACK
#include "msgpack-c/include/msgpack.h"
#endif
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(msgpack_sbuffer_new)
ATSdyncst_mac(msgpack_packer_new)
ATSdyncst_mac(msgpack_sbuffer_write)
ATSdyncst_mac(msgpack_pack_array)
ATSdyncst_mac(atspre_g1int2uint_int_size)
ATSdyncst_mac(msgpack_pack_int)
ATSdyncst_mac(msgpack_pack_true)
ATSdyncst_mac(msgpack_pack_str)
ATSdyncst_mac(msgpack_pack_str_body)
ATSdyncst_mac(msgpack_unpacker_new)
ATSdyncst_mac(msgpack_unpacked_init)
ATSdyncst_mac(msgpack_unpacker_reserve_buffer)
ATSdyncst_mac(msgpack_sbuffer_size)
ATSdyncst_mac(msgpack_unpacker_buffer)
ATSdyncst_mac(msgpack_sbuffer_buffer)
ATSdyncst_mac(msgpack_unpacker_buffer_consumed)
ATSdyncst_mac(msgpack_unpacker_next)
ATSdyncst_mac(atspre_assert_errmsg_bool0)
ATSdyncst_mac(atspre_g0int2int_int_int)
ATSdyncst_mac(atspre_g0int_eq_int)
ATSdyncst_mac(msgpack_unpacked_data)
ATSdyncst_mac(msgpack_object_print)
ATSdyncst_mac(atspre_FILE_stdout)
ATSdyncst_mac(msgpack_unpacked_destroy)
ATSdyncst_mac(msgpack_unpacker_free)
ATSdyncst_mac(msgpack_packer_free)
ATSdyncst_mac(msgpack_sbuffer_free)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
/*
exnconlst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
/*
assumelst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
#if(0)
ATSextern()
atsvoid_t0ype
mainats_void_0() ;
#endif // end of [QUALIFIED]

#if(0)
#if(0)
ATSextern()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)), atstkind_t0ype(atstype_int)) ;
#endif // end of [QUALIFIED]
#endif // end of [TEMPLATE]

ATSstatic()
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__1(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

/*
/home/hwwu/GitHub/msgpack-ats/msgpack.dats: 172(line=12, offs=17) -- 1326(line=44, offs=2)
*/
/*
local: 
global: mainats_void_0$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_void_0()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmp1, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp2, msgpack_packer *) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp4, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp5, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp6, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp7, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp10, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp11, msgpack_unpacker *) ;
ATStmpdec(tmpref12, msgpack_unpacked) ;
// ATStmpdec_void(tmp13) ;
ATStmpdec(tmp14, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp15, atstkind_t0ype(atstype_size)) ;
ATStmpdec(tmp16, atstkind_t0ype(atstype_size)) ;
// ATStmpdec_void(tmp17) ;
ATStmpdec(tmp18, atstkind_type(atstype_ptrk)) ;
ATStmpdec(tmp19, atstkind_type(atstype_ptrk)) ;
// ATStmpdec_void(tmp20) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp22) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp28, msgpack_object) ;
// ATStmpdec_void(tmp29) ;
// ATStmpdec_void(tmp30) ;
// ATStmpdec_void(tmp31) ;
// ATStmpdec_void(tmp32) ;
// ATStmpdec_void(tmp33) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 166(line=12, offs=11) -- 1326(line=44, offs=2)
*/
ATSINSflab(__patsflab_main_void_0):
/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 177(line=12, offs=22) -- 1326(line=44, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 199(line=13, offs=12) -- 221(line=13, offs=34)
*/
ATSINSmove(tmp1, msgpack_sbuffer_new()) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 236(line=14, offs=15) -- 283(line=14, offs=62)
*/
ATSINSmove(tmp2, msgpack_packer_new(ATSPMVrefarg0(tmp1), msgpack_sbuffer_write)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 322(line=16, offs=38) -- 328(line=16, offs=44)
*/
ATSINSmove(tmp4, atspre_g1int2uint_int_size(ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 294(line=16, offs=10) -- 329(line=16, offs=45)
*/
ATSINSmove(tmp3, msgpack_pack_array(ATSPMVrefarg0(tmp2), tmp4)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 339(line=17, offs=10) -- 367(line=17, offs=38)
*/
ATSINSmove(tmp5, msgpack_pack_int(ATSPMVrefarg0(tmp2), ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 377(line=18, offs=10) -- 402(line=18, offs=35)
*/
ATSINSmove(tmp6, msgpack_pack_true(ATSPMVrefarg0(tmp2))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 439(line=19, offs=36) -- 445(line=19, offs=42)
*/
ATSINSmove(tmp8, atspre_g1int2uint_int_size(ATSPMVi0nt(7))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 413(line=19, offs=10) -- 446(line=19, offs=43)
*/
ATSINSmove(tmp7, msgpack_pack_str(ATSPMVrefarg0(tmp2), tmp8)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 498(line=20, offs=52) -- 504(line=20, offs=58)
*/
ATSINSmove(tmp10, atspre_g1int2uint_int_size(ATSPMVi0nt(7))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 456(line=20, offs=10) -- 505(line=20, offs=59)
*/
ATSINSmove(tmp9, msgpack_pack_str_body(ATSPMVrefarg0(tmp2), ATSPMVstring("example"), tmp10)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 523(line=22, offs=17) -- 578(line=22, offs=72)
*/
ATSINSmove(tmp11, msgpack_unpacker_new(ATSPMVextval(MSGPACK_UNPACKER_INIT_BUFFER_SIZE))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 586(line=24, offs=6) -- 594(line=24, offs=14)
*/
/*
ATSINStmpdec(tmpref12) ;
*/
/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 624(line=25, offs=11) -- 654(line=25, offs=41)
*/
ATSINSmove_void(tmp13, msgpack_unpacked_init(ATSPMVrefarg1(ATSPMVptrof(tmpref12)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 708(line=27, offs=53) -- 716(line=27, offs=61)
*/
ATSINSmove(tmp15, atspre_g1int2uint_int_size(ATSPMVi0nt(100))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 665(line=27, offs=10) -- 717(line=27, offs=62)
*/
ATSINSmove(tmp14, msgpack_unpacker_reserve_buffer(ATSPMVrefarg0(tmp11), tmp15)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 730(line=28, offs=13) -- 754(line=28, offs=37)
*/
ATSINSmove(tmp16, msgpack_sbuffer_size(ATSPMVrefarg0(tmp1))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 791(line=29, offs=37) -- 823(line=29, offs=69)
*/
ATSINSmove(tmp18, msgpack_unpacker_buffer(ATSPMVrefarg0(tmp11))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 825(line=29, offs=71) -- 851(line=29, offs=97)
*/
ATSINSmove(tmp19, msgpack_sbuffer_buffer(ATSPMVrefarg0(tmp1))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 764(line=29, offs=10) -- 858(line=29, offs=104)
*/
ATSINSmove_void(tmp17, ATSextfcall(memcpy, (tmp18, tmp19, tmp16))) ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 868(line=30, offs=10) -- 917(line=30, offs=59)
*/
ATSINSmove_void(tmp20, msgpack_unpacker_buffer_consumed(ATSPMVrefarg0(tmp11), tmp16)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 933(line=32, offs=15) -- 975(line=32, offs=57)
*/
ATSINSmove(tmp21, msgpack_unpacker_next(ATSPMVrefarg0(tmp11), ATSPMVrefarg1(ATSPMVptrof(tmpref12)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 986(line=33, offs=11) -- 1028(line=33, offs=53)
*/
ATSINSmove(tmp23, ATSLIB_056_prelude__eq_g0int_int__1__1(tmp21, ATSPMVextval(MSGPACK_UNPACK_SUCCESS))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 986(line=33, offs=11) -- 1028(line=33, offs=53)
*/
ATSINSmove_void(tmp22, atspre_assert_errmsg_bool0(tmp23, ATSCSTSPmyloc("/home/hwwu/GitHub/msgpack-ats/msgpack.dats: 986(line=33, offs=11) -- 1028(line=33, offs=53)"))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 1041(line=34, offs=12) -- 1072(line=34, offs=43)
*/
ATSINSmove(tmp28, msgpack_unpacked_data(ATSPMVrefarg1(ATSPMVptrof(tmpref12)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 1084(line=36, offs=10) -- 1122(line=36, offs=48)
*/
ATSINSmove_void(tmp29, msgpack_object_print(atspre_FILE_stdout, tmp28)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 1132(line=37, offs=10) -- 1163(line=37, offs=41)
*/
ATSINSmove_void(tmp30, ATSextfcall(puts, (ATSPMVstring("END")))) ;
/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 1175(line=39, offs=11) -- 1208(line=39, offs=44)
*/
ATSINSmove_void(tmp31, msgpack_unpacked_destroy(ATSPMVrefarg1(ATSPMVptrof(tmpref12)))) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 1219(line=40, offs=11) -- 1249(line=40, offs=41)
*/
ATSINSmove_void(tmp32, msgpack_unpacker_free(tmp11)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 1261(line=42, offs=11) -- 1287(line=42, offs=37)
*/
ATSINSmove_void(tmp33, msgpack_packer_free(tmp2)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 1299(line=43, offs=11) -- 1323(line=43, offs=35)
*/
ATSINSmove_void(tmpret0, msgpack_sbuffer_free(tmp1)) ;

/*
emit_instr: loc0 = /home/hwwu/GitHub/msgpack-ats/msgpack.dats: 177(line=12, offs=22) -- 1326(line=44, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [mainats_void_0] */

#if(0)
/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 29101(line=802, offs=14) -- 29141(line=802, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$0(level=0)
local: 
global: 
*/
ATSextern()
/*
imparg = tk(4441)
tmparg = S2Evar(tk(4441))
tmpsub = None()
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1(atstkind_t0ype(atstyvar_type(tk)) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp25, atstkind_t0ype(atstyvar_type(tk))) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29088(line=802, offs=1) -- 29141(line=802, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29127(line=802, offs=40) -- 29139(line=802, offs=52)
*/
ATSINSmove(tmp25, PMVtmpltcst(g0int2int<S2Eextkind(atstype_int), S2Evar(tk(4441))>)(arg1)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29110(line=802, offs=23) -- 29141(line=802, offs=54)
*/
ATSINSmove(tmpret24, PMVtmpltcst(g0int_eq<S2Evar(tk(4441))>)(arg0, tmp25)) ;

ATSfunbody_end()
ATSreturn(tmpret24) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1] */
#endif // end of [TEMPLATE]

/*
/usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats: 29101(line=802, offs=14) -- 29141(line=802, offs=54)
*/
/*
local: 
global: eq_g0int_int$1$1(level=1)
local: 
global: 
*/
ATSstatic()
/*
imparg = tk(4441)
tmparg = S2Evar(tk(4441))
tmpsub = Some(tk(4441) -> S2Eextkind(atstype_int))
*/
atstkind_t0ype(atstype_bool)
ATSLIB_056_prelude__eq_g0int_int__1__1(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret24__1, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp25__1, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29088(line=802, offs=1) -- 29141(line=802, offs=54)
*/
ATSINSflab(__patsflab_eq_g0int_int):
/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29127(line=802, offs=40) -- 29139(line=802, offs=52)
*/
ATSINSmove(tmp25__1, atspre_g0int2int_int_int(arg1)) ;

/*
emit_instr: loc0 = /usr/local/lib/ats2-postiats-0.1.4/prelude/DATS/integer.dats({$PATSPRE}/DATS/integer.dats): 29110(line=802, offs=23) -- 29141(line=802, offs=54)
*/
ATSINSmove(tmpret24__1, atspre_g0int_eq_int(arg0, tmp25__1)) ;

ATSfunbody_end()
ATSreturn(tmpret24__1) ;
} /* end of [ATSLIB_056_prelude__eq_g0int_int__1__1] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_init(_057_home_057_hwwu_057_GitHub_057_msgpack_055_ats_057_msgpack_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_home_057_hwwu_057_GitHub_057_msgpack_055_ats_057_msgpack_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_home_057_hwwu_057_GitHub_057_msgpack_055_ats_057_msgpack_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_home_057_hwwu_057_GitHub_057_msgpack_055_ats_057_msgpack_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_home_057_hwwu_057_GitHub_057_msgpack_055_ats_057_msgpack_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE]
#endif /* _ATS_CCOMP_RUNTIME_NONE */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_home_057_hwwu_057_GitHub_057_msgpack_055_ats_057_msgpack_056_dats__dynload() ;
ATSmainats_void_0(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
